#pragma once
// prefix ogg functions to prevent douplicate symbols

#define oggpack_readinit tr_oggpack_readinit
#define oggpack_look  tr_oggpack_look
#define oggpack_adv tr_oggpack_adv
#define oggpack_read tr_oggpack_read
#define oggpack_bytes tr_oggpack_bytes
#define oggpack_bits tr_oggpack_bits
#define oggpack_eop tr_oggpack_eop
#define ogg_sync_create tr_ogg_sync_create
#define ogg_sync_destroy tr_ogg_sync_destroy
#define ogg_sync_reset tr_ogg_sync_reset
#define ogg_sync_bufferin tr_ogg_sync_bufferin
#define ogg_sync_wrote tr_ogg_sync_wrote
#define ogg_sync_pageseek tr_ogg_sync_pageseek
#define ogg_sync_pageout tr_ogg_sync_pageout
#define ogg_stream_pagein tr_ogg_stream_pagein
#define ogg_stream_packetout tr_ogg_stream_packetout
#define ogg_stream_packetpeek tr_ogg_stream_packetpeek
#define ogg_stream_create tr_ogg_stream_create
#define ogg_stream_destroy tr_ogg_stream_destroy
#define ogg_stream_reset tr_ogg_stream_reset
#define ogg_stream_reset_serialno tr_ogg_stream_reset_serialno
#define ogg_stream_eos tr_ogg_stream_eos
#define ogg_page_checksum_set tr_ogg_page_checksum_set
#define ogg_page_version tr_ogg_page_version
#define ogg_page_continued tr_ogg_page_continued
#define ogg_page_bos tr_ogg_page_bos
#define ogg_page_eos tr_ogg_page_eos
#define ogg_page_granulepos tr_ogg_page_granulepos
#define ogg_page_serialno tr_ogg_page_serialno
#define ogg_page_pageno tr_ogg_page_pageno
#define ogg_page_packets tr_ogg_page_packets
#define ogg_packet_release tr_ogg_packet_release
#define ogg_packet_release tr_ogg_packet_release
#define ogg_page_release tr_ogg_page_release
#define ogg_page_dup tr_ogg_page_dup
